import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "avoria-language";
const SUPPORTED_LANGUAGES = new Set(["en", "tr"]);

const tr = {
  "Home": "Ana Sayfa",
  "Video": "Video",
  "Audio": "Ses",
  "Convert": "Dönüştür",
  "Compress": "Sıkıştır",
  "Trim": "Kırp",
  "Speed": "Hız",
  "Crop & Fit": "Kırp ve Sığdır",
  "Merge Videos": "Videoları Birleştir",
  "Extract Audio": "Sesi Ayır",
  "Mute Video": "Videoyu Sessize Al",
  "Volume": "Ses Seviyesi",
  "Replace Audio": "Sesi Değiştir",
  "Main Navigation": "Ana menü",
  "Mobile Navigation": "Mobil menü",
  "Open menu": "Menüyü aç",
  "Close navigation": "Menüyü kapat",
  "Expand sidebar": "Kenar çubuğunu genişlet",
  "Collapse sidebar": "Kenar çubuğunu daralt",
  "Powered by": "Geliştiren",
  "Language": "Dil",
  "Switch language": "Dili değiştir",
  "Enable dark theme": "Koyu temayı aç",
  "Enable light theme": "Açık temayı aç",

  "Your complete media workspace": "Eksiksiz medya çalışma alanınız",
  "Every media tool you need.": "İhtiyacınız olan tüm medya araçları.",
  "None of the complexity.": "Karmaşıklık olmadan.",
  "Convert, compress, trim, crop, merge, fine-tune video and audio — all from one fast, focused workspace.": "Video ve sesi dönüştürün, sıkıştırın, kırpın, birleştirin ve ince ayar yapın — hepsi hızlı ve odaklı tek bir çalışma alanında.",
  "Uploading...": "Yükleniyor...",
  "Start with a video": "Bir videoyla başlayın",
  "Active media in workspace:": "Çalışma alanındaki aktif medya:",
  "Make every frame count.": "Her kareyi değerlendirin.",
  "Sound exactly right.": "Tam istediğiniz gibi ses.",
  "{count} tools": "{count} araç",
  "Change video format": "Video formatını değiştirin",
  "Reduce file size": "Dosya boyutunu azaltın",
  "Frame for any platform": "Her platforma uygun kadraj",
  "Cut your video": "Videonuzu kırpın",
  "Adjust playback speed": "Oynatma hızını ayarlayın",
  "Join clips together": "Klipleri birleştirin",
  "Strip high-bitrate MP3, WAV, FLAC, M4A, or Opus audio tracks from any video.": "Videonun ses parçasını ayırıp seçtiğiniz formatta ayrı bir dosya olarak kaydedin.",
  "Remove every audio track and export a clean, completely silent video.": "Tüm ses parçalarını kaldırıp tamamen sessiz bir video dışa aktarın.",
  "Adjust Volume": "Ses Seviyesini Ayarla",
  "Boost quiet recordings or attenuate loud soundtracks up to 200%.": "Sesi az olan kayıtları yükseltin veya yüksek sesleri %200'e kadar ayarlayın.",
  "Swap or overlay a fresh soundtrack onto your video with optional looping.": "Videonuzun sesini yenisiyle değiştirin; isterseniz sesi döngüye alın.",

  "Drop your media here": "Medyanızı buraya bırakın",
  "or browse from your device": "veya cihazınızdan seçin",
  "Supports MP4, MOV, MKV, WebM, MP3, WAV, FLAC (up to 2GB)": "MP4, MOV, MKV, WebM, MP3, WAV, FLAC desteklenir (en fazla 2 GB)",
  "Upload dropzone": "Dosya yükleme alanı",
  "Uploading media...": "Medya yükleniyor...",
  "Please wait while your media is being uploaded": "Medyanız yüklenirken lütfen bekleyin",
  "Uploaded Media": "Yüklenen Medya",
  "Change current media file": "Mevcut medya dosyasını değiştir",
  "Change file": "Dosyayı değiştir",
  "Media Preview": "Medya Önizleme",
  "Local Preview": "Yerel Önizleme",
  "Your browser does not support video playback.": "Tarayıcınız video oynatmayı desteklemiyor.",
  "Your browser does not support audio playback.": "Tarayıcınız ses oynatmayı desteklemiyor.",
  "Your media is ready": "Medyanız hazır",
  "Your processed file is ready to use.": "İşlenen dosyanız kullanıma hazır.",
  "Download file": "Dosyayı indir",
  "Processing result": "İşlem sonucu",
  "Original Size": "Orijinal Boyut",
  "Processed Size": "İşlenen Boyut",
  "Reduction": "Azalma",
  "Process another file": "Başka bir dosya işle",
  "Processing Error": "İşlem Hatası",
  "Upload Error": "Yükleme Hatası",
  "Retry": "Tekrar dene",
  "Processing your media": "Medyanız işleniyor",
  "Avoria is executing your media transformation...": "Avoria medya dönüştürme işleminizi gerçekleştiriyor...",
  "{progress}% completed": "%{progress} tamamlandı",
  "Video file": "Video dosyası",
  "Audio file": "Ses dosyası",

  "Landscape": "Yatay",
  "Portrait": "Dikey",
  "Square": "Kare",
  "Social": "Sosyal",
  "Aspect Ratio": "En-boy oranı",
  "Select color": "Renk seç",
  "Hex color value": "Hex renk değeri",
  "Select {color}": "{color} rengini seç",
  "Select preset color {color}": "{color} hazır rengini seç",
  "Output Volume Level": "Çıkış Ses Seviyesi",
  "Volume percentage": "Ses yüzdesi",
  "Mute": "Sessiz",
  "Original": "Orijinal",

  "Convert Video & Audio": "Video ve Ses Dönüştür",
  "Upload a video or audio file and convert it to a compatible media container and codec without changing its original content or duration.": "Bir video veya ses dosyası yükleyin; orijinal içeriğini ve süresini değiştirmeden uyumlu bir medya kapsayıcısına ve kodeğe dönüştürün.",
  "Select video or audio to convert": "Dönüştürülecek video veya sesi seçin",
  "Video: MP4, MOV, MKV, WebM, AVI · Audio: MP3, WAV, M4A, AAC, FLAC, OGG, Opus": "Video: MP4, MOV, MKV, WebM, AVI · Ses: MP3, WAV, M4A, AAC, FLAC, OGG, Opus",
  "Converting your video file": "Video dosyanız dönüştürülüyor",
  "Converting your audio file": "Ses dosyanız dönüştürülüyor",
  "Transcoding to {format} ({codecs})...": "{format} ({codecs}) biçimine kodlanıyor...",
  "Your converted video file is ready": "Dönüştürülen video dosyanız hazır",
  "Your converted audio file is ready": "Dönüştürülen ses dosyanız hazır",
  "The new file is ready for playback, editing or sharing.": "Yeni dosya oynatma, düzenleme veya paylaşma için hazır.",
  "Download video file": "Video dosyasını indir",
  "Download audio file": "Ses dosyasını indir",
  "Target Container Format": "Hedef Kapsayıcı Formatı",
  "Select the format you want your video file saved as.": "Video dosyanızın kaydedileceği formatı seçin.",
  "Select the format you want your audio file saved as.": "Ses dosyanızın kaydedileceği formatı seçin.",
  "Convert to {format}": "{format} formatına dönüştür",
  "Upload video or audio to convert": "Dönüştürmek için video veya ses yükleyin",
  "Extension: {extension}, Codecs: {codecs}": "Uzantı: {extension}, Kodekler: {codecs}",
  "Maximum compatibility across all devices and web platforms.": "Tüm cihazlar ve web platformlarıyla en yüksek uyumluluk.",
  "Apple standard format, optimal for editing in Final Cut / Premiere.": "Final Cut ve Premiere düzenlemeleri için ideal Apple standart formatı.",
  "Modern open web format with superior compression for browsers.": "Tarayıcılar için gelişmiş sıkıştırmaya sahip modern açık web formatı.",
  "Flexible container supporting high fidelity and multiple audio streams.": "Yüksek kaliteyi ve birden fazla ses akışını destekleyen esnek kapsayıcı.",
  "Universal compressed audio for playback and sharing.": "Oynatma ve paylaşım için evrensel sıkıştırılmış ses.",
  "Uncompressed PCM audio for editing and archiving.": "Düzenleme ve arşivleme için sıkıştırılmamış PCM ses.",
  "Lossless compressed audio with full source quality.": "Kaynak kalitesini tamamen koruyan kayıpsız sıkıştırılmış ses.",
  "Open audio container supporting Vorbis, Opus and FLAC.": "Vorbis, Opus ve FLAC destekleyen açık ses kapsayıcısı.",
  "Efficient AAC audio for Apple devices and modern players.": "Apple cihazları ve modern oynatıcılar için verimli AAC ses.",
  "Modern high-efficiency audio for web and speech.": "Web ve konuşma için modern, yüksek verimli ses.",

  "Compress Video": "Videoyu Sıkıştır",
  "Upload a video and choose a compression level to reduce its file size for easier storage or sharing. Avoria re-encodes the file and shows how much space you saved.": "Bir video yükleyip sıkıştırma seviyesini seçin. Avoria dosyayı yeniden kodlar ve ne kadar alan kazandığınızı gösterir.",
  "Select video to compress": "Sıkıştırılacak videoyu seçin",
  "Drag & drop or browse high-resolution video": "Yüksek çözünürlüklü videoyu sürükleyip bırakın veya seçin",
  "Compressing video stream": "Video akışı sıkıştırılıyor",
  "Applying rate control and encoder optimization...": "Hız kontrolü ve kodlayıcı optimizasyonu uygulanıyor...",
  "Compressed video ready": "Sıkıştırılan video hazır",
  "Your new file is ready to download.": "Yeni dosyanız indirilmeye hazır.",
  "Download video": "Videoyu indir",
  "Compression Preset": "Sıkıştırma Ayarı",
  "Choose the desired balance between file size savings and visual fidelity.": "Dosya boyutu tasarrufu ile görsel kalite arasındaki dengeyi seçin.",
  "High Quality": "Yüksek Kalite",
  "Visually Lossless": "Kayıpsız",
  "Preserves pristine detail and color accuracy with moderate size reduction.": "Dosya boyutunu belirli ölçüde küçültürken görüntü ayrıntılarını ve renk doğruluğunu korur.",
  "Balanced": "Dengeli",
  "Recommended": "Önerilen",
  "Optimal balance between small file size and sharp visual clarity for sharing.": "Paylaşım için küçük dosya boyutu ile net görüntü arasında ideal denge.",
  "Small File": "Küçük Dosya",
  "Maximum Savings": "En Yüksek Tasarruf",
  "Compact video size ideal for email attachments and bandwidth-constrained apps.": "E-posta ekleri ve bant genişliği sınırlı uygulamalar için ideal kompakt video boyutu.",
  "Upload a video to compress": "Sıkıştırmak için video yükleyin",

  "Crop to Fill": "Dolduracak Şekilde Kırp",
  "Fills the entire target aspect ratio frame by center-cropping edges.": "Kenarları merkezden kırparak hedef çerçevenin tamamını doldurur.",
  "Fit Inside (Letterbox/Pillarbox)": "İçine Sığdır",
  "Keeps 100% of video content visible, filling empty outer margins.": "Videoya arka plan ekleyerek istenen boyuta sığdırır.",
  "Solid Color Background": "Düz Renk Arka Plan",
  "Click to choose any color for the outer bars.": "Dış çubuklar için bir renk seçin.",
  "Blurred Video Background": "Bulanık Video Arka Planı",
  "Generates an aesthetic Gaussian-blurred background from the video.": "Videodan estetik, Gaussian bulanıklığa sahip bir arka plan oluşturur.",
  "Upload a video, choose the aspect ratio you need, then crop it to fill the frame or fit it with a color or blurred background for different screens and social platforms.": "Videonuzu yükleyin ve istediğiniz en-boy oranını seçin. Görüntüyü çerçeveyi dolduracak şekilde kırpabilir; renkli veya bulanık bir arka planla çerçeveye sığdırabilirsiniz.",
  "Select video to reframe": "Yeniden kadrajlanacak videoyu seçin",
  "Drag & drop or browse video file": "Video dosyasını sürükleyip bırakın veya seçin",
  "Rendering aspect ratio geometry": "En-boy oranı işleniyor",
  "Target ratio: {ratio} with {mode}...": "Hedef oran: {ratio}, mod: {mode}...",
  "center crop": "merkezden kırpma",
  "fit ({background})": "sığdırma ({background})",
  "color": "renk",
  "blur": "bulanık",
  "Reframed video ready": "Yeniden kadrajlanan video hazır",
  "Preview your {ratio} video below or download the finished file.": "{ratio} videonuzu aşağıda önizleyin veya tamamlanan dosyayı indirin.",
  "Reframed video ({ratio})": "Yeniden kadrajlanan video ({ratio})",
  "Target Aspect Ratio": "Hedef En-Boy Oranı",
  "Select your target canvas format.": "Hedef tuval formatınızı seçin.",
  "Framing Mode": "Kadraj Modu",
  "Choose how content aligns within the target aspect ratio.": "İçeriğin hedef en-boy oranına nasıl yerleşeceğini seçin.",
  "Background Style": "Arka Plan Stili",
  "Fill style for outer letterbox/pillarbox margins.": "Dış kenar boşlukları için dolgu stilini seçin.",
  "Choose background color": "Arka plan rengini seç",
  "Process Crop & Fit ({ratio})": "Kırp ve Sığdır ({ratio})",
  "Upload a video to reframe": "Yeniden kadrajlamak için video yükleyin",

  "Extract Audio Track": "Ses Parçasını Ayır",
  "Upload a video, choose MP3, WAV, FLAC, M4A, Opus or OGG, and extract its soundtrack as a separate audio file for listening, editing or reuse.": "Bir video yükleyin ve içindeki ses parçasını MP3, WAV, FLAC, M4A, Opus veya OGG formatında ayrı bir ses dosyası olarak çıkarın.",
  "Select video file": "Video dosyası seçin",
  "Drag & drop or browse video containing audio": "Ses içeren videoyu sürükleyip bırakın veya seçin",
  "Extracting audio track": "Ses parçası ayrılıyor",
  "Transcoding audio stream to high-quality {format}...": "Ses akışı yüksek kaliteli {format} formatına dönüştürülüyor...",
  "Audio extraction complete": "Ses ayırma tamamlandı",
  "Listen to your extracted {format} audio below or download the finished file.": "Ayırılan {format} sesi aşağıda dinleyin veya tamamlanan dosyayı indirin.",
  "Download audio": "Sesi indir",
  "Extracted {format} audio": "Ayırılan {format} ses",
  "Output Audio Format": "Çıkış Ses Formatı",
  "Choose the destination audio container and codec.": "Hedef ses kapsayıcısını ve kodeğini seçin.",
  "Extract as {format}": "{format} olarak ayır",
  "Upload video to extract audio": "Sesi ayırmak için video yükleyin",
  "MP3 Audio": "MP3 Ses",
  "Universal": "Evrensel",
  "Standard 320kbps MP3 compatible with every audio player.": "Tüm ses oynatıcılarla uyumlu standart 320 kbps MP3.",
  "WAV (Uncompressed)": "WAV (Sıkıştırılmamış)",
  "Studio Master": "Stüdyo Master",
  "Lossless uncompressed PCM audio preserving pristine frequency response.": "Frekans tepkisini koruyan kayıpsız, sıkıştırılmamış PCM ses.",
  "FLAC (Lossless)": "FLAC (Kayıpsız)",
  "High Fidelity": "Yüksek Sadakat",
  "Bit-perfect lossless compression for audiophile preservation.": "Kaynağı birebir koruyan kayıpsız sıkıştırma.",
  "Apple Standard": "Apple Standardı",
  "Efficient AAC codec ideal for iPhone, iPad, and macOS ecosystems.": "iPhone, iPad ve macOS ekosistemi için ideal, verimli AAC kodeği.",
  "Opus Audio": "Opus Ses",
  "Modern Web": "Modern Web",
  "State-of-the-art interactive audio codec with ultra-low latency & high efficiency.": "Çok düşük gecikmeli ve yüksek verimli modern etkileşimli ses kodeği.",
  "Open Standard": "Açık Standart",
  "Open-source audio container favored by games and web apps.": "Oyunlar ve web uygulamalarında tercih edilen açık kaynaklı ses kapsayıcısı.",

  "First Video": "İlk Video",
  "Match 1st Clip": "İlk Kliple Eşleştir",
  "Upload two or more video clips, arrange them in the order you want, select a shared canvas ratio, and combine them into one continuous video file.": "En az iki video klibi yükleyin, istediğiniz sıraya koyun, ortak tuval oranını seçin ve tek bir video dosyasında birleştirin.",
  "Failed to upload video.": "Video yüklenemedi.",
  "Upload Error": "Yükleme Hatası",
  "Concatenating video sequences": "Video dizileri birleştiriliyor",
  "Harmonizing {count} clips to {ratio} aspect ratio...": "{count} klip {ratio} en-boy oranına uyarlanıyor...",
  "Merged video ready": "Birleştirilen video hazır",
  "Preview your combined video below or download the finished file.": "Birleştirilen videoyu aşağıda önizleyin veya tamamlanan dosyayı indirin.",
  "Merged video": "Birleştirilen video",
  "Video Playlist ({count})": "Video Listesi ({count})",
  "Minimum 2 videos required": "En az 2 video gerekli",
  "Ready to merge": "Birleştirmeye hazır",
  "Move clip up": "Klibi yukarı taşı",
  "Move clip down": "Klibi aşağı taşı",
  "Remove clip": "Klibi kaldır",
  "No videos added yet. Upload at least 2 videos below.": "Henüz video eklenmedi. Aşağıdan en az 2 video yükleyin.",
  "Add your first video clip": "İlk video klibinizi ekleyin",
  "Add another video clip": "Başka bir video klibi ekleyin",
  "Upload clips in order or rearrange them using controls above": "Klipleri sırayla yükleyin veya yukarıdaki kontrollerle yeniden sıralayın",
  "Output Canvas Aspect Ratio": "Çıkış Tuvali En-Boy Oranı",
  "Normalize merged clips to a uniform aspect ratio.": "Birleştirilen klipleri ortak bir en-boy oranına uyarlayın.",
  "Merge {count} Videos": "{count} Videoyu Birleştir",
  "Upload at least 2 videos to merge": "Birleştirmek için en az 2 video yükleyin",

  "Upload a video to remove every embedded audio stream and create a completely silent copy while keeping the original picture and playback duration unchanged.": "Bir video yükleyin; videodaki tüm sesleri kaldırarak görüntü kalitesini ve süresini değiştirmeden sessiz bir kopya oluşturun.",
  "Select video to mute": "Sessize alınacak videoyu seçin",
  "Removing audio streams": "Ses akışları kaldırılıyor",
  "Generating a completely silent video output...": "Tamamen sessiz video çıktısı oluşturuluyor...",
  "Video muted successfully": "Video başarıyla sessize alındı",
  "Preview your silent video below or download the finished file.": "Sessiz videonuzu aşağıda önizleyin veya tamamlanan dosyayı indirin.",
  "Muted video": "Sessize alınmış video",
  "Strip Audio Stream": "Ses Akışını Kaldır",
  "All embedded soundtracks and commentary will be eliminated. Visual quality is preserved.": "Tüm gömülü sesler ve konuşmalar kaldırılır. Görsel kalite korunur.",
  "Mute and Export Video": "Videoyu Sessize Al ve Dışa Aktar",
  "Upload video to mute": "Sessize almak için video yükleyin",

  "Adjust Playback Speed": "Oynatma Hızını Ayarla",
  "Upload a video or audio file, choose one of the supported playback speeds from 0.5x to 4x, and create a faster or slower version while keeping voices and music natural.": "Bir video veya ses dosyası yükleyin, 0,5x ile 4x arasında bir oynatma hızı seçin ve sesleri doğal tutarak daha hızlı veya yavaş bir sürüm oluşturun.",
  "Select video or audio to adjust speed": "Hızı ayarlanacak video veya sesi seçin",
  "Drag & drop or browse media file": "Medya dosyasını sürükleyip bırakın veya seçin",
  "Recalculating frame timestamps": "Medya zamanlaması ayarlanıyor",
  "Applying {speed}x tempo transformation...": "{speed}x tempo dönüşümü uygulanıyor...",
  "Adjusted media ready": "Hızı ayarlanan medya hazır",
  "Preview your {speed}x result below or download the finished file.": "{speed}x sonucu aşağıda önizleyin veya tamamlanan dosyayı indirin.",
  "Download media": "Medyayı indir",
  "Speed Multiplier": "Hız Çarpanı",
  "Speed multiplier": "Hız çarpanı",
  "Apply {speed}x Playback Speed": "{speed}x oynatma hızı uygula",
  "Upload media to adjust speed": "Hızı ayarlamak için medya yükleyin",

  "Trim Media": "Medyayı Kırp",
  "Upload a video or audio file, enter exact start and end times, and export only the section you want without keeping the unwanted beginning or ending.": "Bir video veya ses dosyası yükleyin, başlangıç ve bitiş zamanlarını girin ve yalnızca istediğiniz bölümü dışa aktarın.",
  "Select video or audio to trim": "Kırpılacak video veya sesi seçin",
  "Trimming media track": "Medya parçası kırpılıyor",
  "Cutting from {start}s to {end}s...": "{start}s ile {end}s arası kesiliyor...",
  "Trimmed media ready": "Kırpılan medya hazır",
  "Preview your selected clip below or download the finished file.": "Seçilen klibi aşağıda önizleyin veya tamamlanan dosyayı indirin.",
  "Trimmed {type}": "Kırpılan {type}",
  "Cut Boundaries": "Kesim Sınırları",
  "Output Duration:": "Çıktı Süresi:",
  "Start Timestamp (seconds)": "Başlangıç Zamanı (saniye)",
  "End Timestamp (seconds)": "Bitiş Zamanı (saniye)",
  "End timestamp must be strictly greater than start timestamp.": "Bitiş zamanı başlangıç zamanından büyük olmalıdır.",
  "Start time must be less than the media duration ({duration}s).": "Başlangıç zamanı medya süresinden ({duration}s) küçük olmalıdır.",
  "End time cannot exceed the media duration ({duration}s).": "Bitiş zamanı medya süresini ({duration}s) aşamaz.",
  "Start and end times must be zero or greater.": "Başlangıç ve bitiş zamanları sıfır veya daha büyük olmalıdır.",
  "Trim Media ({duration}s)": "Medyayı Kırp ({duration}s)",
  "Upload media to trim": "Kırpmak için medya yükleyin",

  "Adjust Audio Volume": "Ses Seviyesini Ayarla",
  "Upload a video or audio file and set the volume from 0% to 200% to mute, lower or boost its sound, then export a new file at your chosen level.": "Bir video veya ses dosyası yükleyin; sesi kapatmak, azaltmak veya yükseltmek için seviyeyi %0 ile %200 arasında ayarlayın.",
  "Select video or audio file": "Video veya ses dosyası seçin",
  "Adjusting audio gain": "Ses kazanımı ayarlanıyor",
  "Applying {volume}% gain multiplier...": "%{volume} ses kazanımı uygulanıyor...",
  "Volume adjustment complete": "Ses seviyesi ayarlandı",
  "Preview your {volume}% volume result below or download the finished file.": "%{volume} ses sonucunu aşağıda önizleyin veya tamamlanan dosyayı indirin.",
  "{volume}% volume {type}": "%{volume} ses seviyeli {type}",
  "Gain Multiplier": "Ses Kazanımı",
  "Set Volume to {volume}%": "Ses seviyesini %{volume} yap",
  "Upload media to adjust volume": "Ses seviyesini ayarlamak için medya yükleyin",

  "Upload a base video and a new audio track to replace the original soundtrack. You can also loop shorter audio so it continues for the full video duration.": "Orijinal sesi değiştirmek için temel videoyu ve yeni ses parçasını yükleyin. Kısa sesi video boyunca devam etmesi için döngüye alabilirsiniz.",
  "Failed to upload audio file.": "Ses dosyası yüklenemedi.",
  "Multiplexing new audio track": "Yeni ses parçası videoya ekleniyor",
  "Aligning replacement audio with video stream...": "Yeni ses video akışıyla hizalanıyor...",
  "Audio replaced successfully": "Ses başarıyla değiştirildi",
  "Preview the video with its new soundtrack below or download the finished file.": "Videoyu yeni sesiyle aşağıda önizleyin veya tamamlanan dosyayı indirin.",
  "Video with replaced audio": "Sesi değiştirilmiş video",
  "1. Base Video File": "1. Temel Video Dosyası",
  "Select base video file": "Temel video dosyasını seçin",
  "Drag & drop or browse video": "Videoyu sürükleyip bırakın veya seçin",
  "2. Replacement Audio Track": "2. Yeni Ses Parçası",
  "Select replacement audio file": "Yeni ses dosyasını seçin",
  "Drag & drop MP3, WAV, FLAC, M4A, Opus, or AAC": "MP3, WAV, FLAC, M4A, Opus veya AAC dosyasını sürükleyip bırakın",
  "Audio Track": "Ses Parçası",
  "Change audio": "Sesi değiştir",
  "Audio Loop Settings": "Ses Döngüsü Ayarları",
  "Loop soundtrack": "Ses parçasını döngüye al",
  "Repeat audio if it is shorter than the total video duration.": "Ses toplam video süresinden kısaysa tekrarla.",
  "Replace Audio Track": "Ses Parçasını Değiştir",
  "Upload base video first": "Önce temel videoyu yükleyin",
  "Upload replacement audio track": "Yeni ses parçasını yükleyin",

  "Landscape (1920×1080)": "Yatay (1920×1080)",
  "Portrait (1080×1920)": "Dikey (1080×1920)",
  "Square (1080×1080)": "Kare (1080×1080)",
  "Social (1080×1350)": "Sosyal (1080×1350)",

  "Please select a file to upload.": "Lütfen yüklemek için bir dosya seçin.",
  "Unsupported file type ({ext}). Allowed: MP4, MOV, MKV, WebM, MP3, WAV, FLAC, etc.": "Desteklenmeyen dosya türü ({ext}). İzin verilenler: MP4, MOV, MKV, WebM, MP3, WAV, FLAC vb.",
  "File exceeds maximum allowed size (2GB).": "Dosya izin verilen en büyük boyutu (2 GB) aşıyor.",
  "Failed to upload media file.": "Medya dosyası yüklenemedi.",
  "Media processing failed.": "Medya işleme başarısız oldu.",
  "Failed to start processing job.": "Medya işlemi başlatılamadı.",
  "Processing finished, but its status could not be checked. Please try again.": "İşlem tamamlandı ancak durumu kontrol edilemedi. Lütfen tekrar deneyin.",
  "Error checking job status.": "İşlem durumu kontrol edilirken hata oluştu.",
};

const LanguageContext = createContext(null);

function getInitialLanguage() {
  const saved = window.localStorage.getItem(STORAGE_KEY);
  if (SUPPORTED_LANGUAGES.has(saved)) return saved;
  return navigator.language?.toLowerCase().startsWith("tr") ? "tr" : "en";
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((nextLanguage) => {
    if (SUPPORTED_LANGUAGES.has(nextLanguage)) setLanguageState(nextLanguage);
  }, []);

  const t = useCallback((key, variables = {}) => {
    const template = language === "tr" ? (tr[key] || key) : key;
    return Object.entries(variables).reduce(
      (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
      template,
    );
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
